/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager */

#ifndef _Included_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
#define _Included_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_MAX_LOOP_DEVICES
#define edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_MAX_LOOP_DEVICES 256L
/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    removeLoopback
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_removeLoopback
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    losetup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_losetup
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    findFreeLoopback
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_findFreeLoopback
  (JNIEnv *, jobject);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    removeLogicalVolume
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_removeLogicalVolume
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    reduceVolumeGroup
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_reduceVolumeGroup
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    removePhysicalVolume
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_removePhysicalVolume
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    createVolumeFromLv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_createVolumeFromLv
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    enableLogicalVolume
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_enableLogicalVolume
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    disableLogicalVolume
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_disableLogicalVolume
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    removeVolumeGroup
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_removeVolumeGroup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager
 * Method:    getLvmVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_ucsb_eucalyptus_storage_fs_FileSystemStorageManager_getLvmVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
